### ISSUE TITLE
ModuleNotFoundError: No module named 'snowflake.ml'

### ISSUE THREAD

**Issue by just4jc** [cromano8/Snowflake_ML_Intro#16]
followed your instructions but received an error - ModuleNotFoundError: No module named 'snowflake.ml'
from this line ----> [4](vscode-notebook-cell:?execution_count=1&line=4) from snowflake.ml.utils.connection_params import SnowflakeLoginOptions

**Comment by sfc-gh-twhite** [comment]
It may not have properly installed that module or it could be that you are not using the same Python environment. 

Can you try running `pip install snowflake-ml-python`?

**Comment by just4jc** [comment]
thanks the problem went away

**Comment by just4jc** [comment]
closing this thanks
