### ISSUE TITLE
check_and_update function in 3_Deployment.ipynb fails if registry already have models

### ISSUE THREAD

**Issue by sfc-gh-mstellwall** [cromano8/Snowflake_ML_Intro#19]
If you already have models in the database and schema used for registry it will fail, since it assume only the titanic model can be there.

If changing the code so the dataframe is filtered on titanic will fix it:
```
reg_df = reg.show_models()

# Define model name and version
model_name = "titanic"
# Only get the model_name model
reg_model_versions_df = reg_df[reg_df['name'] == model_name]

model_version = check_and_update(reg_model_versions_df)
```

**Comment by cromano8** [comment]
Ah you're right, we did this in our last one and had to change it with the new registry, good catch
