### ISSUE TITLE
How to connect Session

### ISSUE THREAD

**Issue by fti-sbargule** [cromano8/Snowflake_ML_Intro#9]
-  how to connect snowflake server 
![Screenshot from 2024-01-19 17-04-29](https://github.com/cromano8/Snowflake_ML_Intro/assets/121230355/d84dcf86-1367-4978-8a12-c0c4607b6dfa)

**Comment by cromano8** [comment]
Did you edit your .env file with your own credentials?

**Comment by fti-sbargule** [comment]
ok thanks
